### ISSUE TITLE
Consider dropping `use` from headings

### ISSUE THREAD

**Issue by cem2ran** [nikgraf/react-hooks#11]
For easier scanning/readability consider dropping the `use` prefix from the hook headings.

e.g. `useDeviceMotion` -> `DeviceMotion`

The code snippets themselves make the usage/name quite clear.

**Comment by nikgraf** [comment]
could work if we have usage section or so

**Comment by nikgraf** [comment]
Let's not do it. The use prefix is quite essential for hooks.
