### ISSUE TITLE
Add Google Analytics without Cookie Tracking

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/react-hooks#27]

**Comment by M0nica** [comment]
@nikgraf Is it possible to implement Google Analytics without cookie tracking? Would having the ability for users opt-out of sharing cookies be sufficient? If so, I'd be interested in implementing this functionality.

**Comment by nikgraf** [comment]
yeah, that said I first need to sign up for an ID.

To get back to your question: Yes, it's possible and if you anonymize the IP as well it's even GDPR compliant afaik. We recently did it here https://github.com/ReasonVienna/reason-conf-2019/pull/71/files

**Comment by nikgraf** [comment]
@M0nica just signed up for Google Analytics. This is the standard tracking snippet:

```js
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-128821753-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-128821753-1');
</script>
```
