### ISSUE TITLE
Potential additions

### ISSUE THREAD

**Issue by jacob-ebey** [nikgraf/react-hooks#38]
This is a cool celection you got going. I published a package thats hosted at: https://github.com/jacob-ebey/react-hook-utils

It introduces the idea of a global reducer that may be of interest to add.

**Comment by nikgraf** [comment]
@jacob-ebey thanks :)

Can yours here by opening a PR? The file to extend is here: https://github.com/nikgraf/react-hooks/blob/master/hooks.json

**Comment by jacob-ebey** [comment]
Opened pull-request #40

**Comment by jacob-ebey** [comment]
In the react-hook-utils package I published, there is also a "usePromise". It differs from the one currently published in returning a loading parameter. It is also tested.

Should I add it as another entry, or update the one there to point to the react-hook-utils package?

**Comment by jacob-ebey** [comment]
Actually, I was thinking you had a different one linked. The one in the react-hook-utils package follows conventions a bit more by returning an array structured as such: [data, error, loading], instead of an object. Thoughts?

**Comment by jacob-ebey** [comment]
PR out.

**Comment by nikgraf** [comment]
just merged it 👏
