### ISSUE TITLE
Scrambled links

### ISSUE THREAD

**Issue by reaysawa** [nikgraf/react-hooks#69]
### Firefox 66.0b9 - Ubuntu 18.04
**Current Behavior**
1. Load the page
2. Links to the hooks' repositories will be scrambled.

**Additional context/Screenshots**

_**As you can see at the bottom URL indicator, the links from the hooks are all scrambled.**_

![image](https://user-images.githubusercontent.com/17429390/53201291-5840ff80-3602-11e9-83ac-a9e51197fa40.png)

As to why this might be happening, I noticed hooks are being sorted alphabetically after the page loads. Maybe it is related to that?

**Comment by stereobooster** [comment]
Can you be more specific. What do you mean by "scrambled"?

**Comment by nikgraf** [comment]
@reaysawa can you verify this is solved after merging this: https://github.com/nikgraf/react-hooks/pull/84

**Comment by reaysawa** [comment]
@nikgraf I'm no longer able to reproduce the issue. Thanks for fixing it!

**Comment by nikgraf** [comment]
Thanks for reporting it
