### ISSUE TITLE
useTimer hook links are flipped

### ISSUE THREAD

**Issue by nikgraf** [nikgraf/react-hooks#78]
@nikgraf When we look at [https://nikgraf.github.io/react-hooks/](https://nikgraf.github.io/react-hooks/), and I fly over the link to my new hook, it points to the hook link below, and vice versa. Still, the content of the JSON is correct. Maybe the link below should be named "reactTimerHook"?

_Originally posted by @thibaultboursier in https://github.com/nikgraf/react-hooks/pull/77#issuecomment-468925940_

**Comment by stereobooster** [comment]
Did you use filter? If yes, there is a bug in how we use `key` property. It is fixed in my PR

**Comment by nikgraf** [comment]
@stereobooster ahh yeah, this PR solves the issue: https://github.com/nikgraf/react-hooks/pull/84

**Comment by thibaultboursier** [comment]
Thanks!
